version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - wiki
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html
  wiki:
    image: hidelberq/wiki
    ports:
      - "8080:8080"
    env_file: ./wiki/.env
    environment:
      DOCKER: "true"
    volumes:
      - /usr/share/hidel-wiki-item:/usr/share/hidel-wiki-item

