import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("aitter", "routes/aitter.tsx"),
	route("debug", "routes/debug.tsx"),
	route("hero-image/:date", "routes/hero-image.ts"),
	route("daily-track", "routes/daily-track.tsx"),
	route("daily-track/audio/:date/:type", "routes/daily-track-audio.ts"),
	route("api/suno-callback", "routes/api.suno-callback.ts"),
	route("book-photo/*", "routes/book-photo.ts"),
	route("whitespace-remover", "routes/whitespace-remover.tsx"),
	route("shogi", "routes/shogi.tsx"),
	route("shogi/local", "routes/shogi.local.tsx"),
	route("shogi/minishogi/local", "routes/shogi.minishogi-local.tsx"),
	route("shogi/minishogi/game/:gameId", "routes/shogi.minishogi-game.tsx"),
	route("shogi/game/:gameId", "routes/shogi.game.tsx"),
	route("tsundoku_2_0", "routes/books.tsx"),
	route("tsundoku_2_0/my", "routes/books.my.tsx"),
	route("tsundoku_2_0/my/add", "routes/books.my-add.tsx"),
	route("tsundoku_2_0/my/photo-add", "routes/books.my-photo-add.tsx"),
	route("api/tsundoku_2_0/recognize", "routes/api.books-recognize.ts"),
	route("tsundoku_2_0/my/book/:personalBookId", "routes/books.my-detail.tsx"),
	route("tsundoku_2_0/:groupCode", "routes/books.group.tsx"),
	route("tsundoku_2_0/:groupCode/add", "routes/books.add.tsx"),
	route("tsundoku_2_0/:groupCode/add-from-personal", "routes/books.group-add-from-personal.tsx"),
	route("tsundoku_2_0/:groupCode/book/:bookId", "routes/books.detail.tsx"),
	route("tsundoku_2_0/feed", "routes/books.feed.tsx"),
	route("tsundoku_2_0/reviews", "routes/books.reviews.tsx"),
	route("tsundoku_2_0/review/:reviewId", "routes/books.review.tsx"),
	route("tsundoku_2_0/my/book/:personalBookId/review", "routes/books.my-review.tsx"),
	route("tsundoku_2_0/users", "routes/books.users.tsx"),
	route("tsundoku_2_0/user/:memberId", "routes/books.user.tsx"),
	route("tsundoku_2_0/settings", "routes/books.settings.tsx"),
	route("rhythm", "routes/rhythm.tsx"),
	route("api/activity", "routes/api.activity.ts"),
	route("api/tsundoku_2_0/search", "routes/api.books-search.ts"),
	route("api/tsundoku_2_0/seed", "routes/api.books-seed.ts"),
] satisfies RouteConfig;
